### PR TITLE
Fix the Pages directory path

### PR DESCRIPTION
**Pull request by lewing**

### CODE REVIEW

**Comment by lewing** [comment]
cc @sebastienros

**Comment by lewing** [comment]
I don't have permissions to request reviewers etc.

**Comment by sebastienros** [comment]
You can join this team if you want to push on the repos or approve some PRs from aspnetcore: https://repos.opensource.microsoft.com/orgs/dotnet/teams/aspnet-team

**Comment by sebastienros** [comment]
Thank you. I restored all the runs on the CI and will let you know if that worked.

**Comment by lewing** [comment]
@sebastienros as a heads up this change was reverted in the templates post rc2 so this will likely need to be reverted sometime soon.

**Comment by sebastienros** [comment]
Benchmarks are using nightly builds, so very soon if on `main`

**Pull request merged**
