### PR TITLE
Flip NoPGO to PGO in Stage1

### PR DESCRIPTION
**Pull request by EgorBo**
These `No PGO` didn't make any sense - PGO is not enabled by default.

cc @sebastienros

### CODE REVIEW

**Comment by sebastienros** [comment]
@eerhardt you own these, better if you know what is necessary here

**Review by eerhardt — APPROVED** [review]
This would make sense why we were getting the same results between `Stage1` and `Stage1NoPgo`.

Note that our NativeAOT goal is "within 5% RPS of the default CoreCLR", so we won't be comparing NativeAOT to these, but it would be beneficial to get numbers on enabling PGO.

**Comment by EgorBo** [comment]
> Note that our NativeAOT goal is "within 5% RPS of the default CoreCLR"

It seems to be overdone on arm already 😄 
image

**Comment by eerhardt** [comment]
Yeah - we don't know why/how NativeAOT is getting better RPS numbers on Ampere Linux. If you have any insights, they would be appreciated. 😄

**Pull request merged**
