### PR TITLE
Updating certificates

### PR DESCRIPTION
**Pull request by sebastienros**
Current one is out of date.
This one is valid for 100 years.
Key size of 4096 bits.

@Tratcher do you know if the key size impacts the traffic perf?

### CODE REVIEW

**Review by HaoK — APPROVED** [review]
Nice 4.5x rps gains :)

**Comment by Tratcher** [comment]
> @Tratcher do you know if the key size impacts the traffic perf?

I know it can affect the negotiated protocol version which could get you very different results.

**Pull request merged**
