### PR TITLE
Use cached repsonse

### PR DESCRIPTION
**Pull request by benaadams**

### CODE REVIEW

**Comment by nathana1** [comment]
Looks fine to me.

/cc @mikeharder

**Comment by mikeharder** [comment]
@benaadams: Seems fine, but does this result in a measurable improvment?

**Comment by benaadams** [comment]
> HttpContext.Response is already a simple field getter?

It isn't yet... https://github.com/aspnet/HttpAbstractions/pull/704

**Comment by mikeharder** [comment]
@benaadams: Assuming this is the correct class, how is this not a simple field getter?

https://github.com/aspnet/HttpAbstractions/blob/dev/src/Microsoft.AspNetCore.Http/DefaultHttpContext.cs#L101

Also, I cannot detect any improvement in RPS from this change.

**Comment by benaadams** [comment]
Ahh.. you are right its the next bit that is the look up.

**Pull request closed without merging**
