### PR TITLE
UseServer(string) was removed

### PR DESCRIPTION
**Pull request by rynowak**
Changing to call kestrel directly for now to unblock perf runs

### CODE REVIEW

**Comment by rynowak** [comment]
Going to merge this to unblock perf testing, will follow up on the right thing to do here.

**Comment by rynowak** [comment]
@davidfowl - you removed this `UseServer(string)` - what should this code do instead?

@mikeharder - is being able to set the server at the command line still relevant?

**Comment by mikeharder** [comment]
@rynowak: I doubt anyone needs to set the server at the command line, but I wasn't the original author of benchmarks.  @DamianEdwards?

**Comment by rynowak** [comment]
IMO let's just resolve to leave this as-is. If someone needs it in the future, I'm not sure we'll be able to envision their needs today.

**Pull request merged**
