### PR TITLE
change JSON scenario to StreamWriter for better scalability

### LINKED ISSUE #99: middleware json test not scaling on 48 cores
This is a regression due my change yesterday.  This is due to https://github.com/aspnet/Mvc/issues/4660.  HttpResponseStreamWriter doesn't scale at this number of cores due to contention in the ArrayPool.

### PR DESCRIPTION
**Pull request by nathana1**
Resolves #99.

See also https://github.com/aspnet/Mvc/issues/4660.

/cc @mikeharder @halter73 @DamianEdwards

### CODE REVIEW

**Comment by halter73** [comment]
:+1: Adding the Content-Length back also means that Kestrel doesn't have to chunk the response.

**Comment by mikeharder** [comment]
Why did Content-Length change from `30` before either of your changes, to `27` after this change?  Was this intentional or accidental?

**Comment by mikeharder** [comment]
:shipit:

**Comment by nathana1** [comment]
Resolved with https://github.com/aspnet/benchmarks/commit/ec5cdea72d32f6f441037ec7fa2495a4bf401b43

**Pull request closed without merging**
