### PR TITLE
Use PooledContextFactory

### PR DESCRIPTION
**Pull request by benaadams**
Also needs https://github.com/aspnet/HttpAbstractions/pull/501 to work

Took out `SupportsSendFile` as it doesn't exist anymore

/cc @DamianEdwards

### CODE REVIEW

**Comment by benaadams** [comment]
Pre-allocations for DefaultContext 1.12MB

before-allocs

Post-allocations for DefaultContext 160KB
 
after-allocs

Almost all of which is logging scope

before-allocs

Not quite sure what's going on with ThreadStatic, but don't use it much - take the locks out and it goes a bit weird.

**Comment by AspNetSmurfLab** [comment]
Mixed results with this. For non-pipelined tests it seems to improve things, but for pipelined tests it makes this much worse (~10% drop in RPS).

**Comment by rynowak** [comment]
Sounds like contention yo

**Comment by benaadams** [comment]
Interesting. I had to put the locks in else the `ThreadStatic` was behaving weird; i.e. not behaving as one. Contention would make sense if it wasn't.

Need to do some investigation and might need to raise a corelcr bug.

**Comment by benaadams** [comment]
Rookie mistake - didn't actually make the `ThreadStatic` `static`

**Comment by DamianEdwards** [comment]
@benaadams would you mind rebasing this so we can re-measure pls?

**Comment by benaadams** [comment]
O_o did I rebase on wrong thing?

**Comment by benaadams** [comment]
Submitted new PR  #49

**Pull request closed without merging**
