### PR TITLE
Adds new EF explicit SQL scenario.

### PR DESCRIPTION
**Pull request by anpete**

### CODE REVIEW

**Comment by mikeharder** [comment]
@anpete: Sorry for the delay.  Did you still want to merge this?

**Comment by mikeharder** [comment]
@anpete: Ping

**Comment by anpete** [comment]
@mikeharder Yes. I will rebase and re-push.

**Comment by mikeharder** [comment]
@anpete: Ping again.  We can also close the PR if we want to defer this until later.

**Comment by anpete** [comment]
Will defer for now.

**Pull request closed without merging**
