### PR TITLE
Add TE Performance Tests Using Composite Images

### PR DESCRIPTION
**Pull request by ivdiazsa**
This PR is for issue #1849. It adds a new Middleware Dockerfile, which targets the newly released composite images, and enables some scenarios to run in TE using them in containers.

### CODE REVIEW

**Comment by ivdiazsa** [comment]
Here's the PR to work on adding the composites to TE @sebastienros

**Comment by ivdiazsa** [comment]
cc @trylek

**Comment by sebastienros** [comment]
Have you tried it with crank by using the `--application.source.repository` and ``--application.source.branchOrCommit` arguments pointingto your fork/branch?

**Comment by sebastienros** [comment]
Then you can change [containers-scenarios.yml](https://github.com/aspnet/Benchmarks/blob/main/build/containers-scenarios.yml) to add the two new scenarios that you configured

**Pull request merged**
