### PR TITLE
Add NpgsqlCommand caching for fortunes

### PR DESCRIPTION
**Pull request by vonzshik**
@roji could you run this and see whether it actually helps?

### CODE REVIEW

**Comment by roji** [comment]
Tried runnin this - it errors a lot. If this doesn't repro for you locally I can try to find out why on the perf lab. But I'm also available to just do quick runs if you want to iterate; just one think - add commits to this PR rather than amending, since there's some problematic caching going on somewhere.

**Comment by roji** [comment]
The @roji bot says:

| db                  | baseline | tls-command-caching |        |
| ------------------- | -------- | ------------------- | ------ |
| CPU Usage (%)       |       34 |                  34 |  0.00% |
| Cores usage (%)     |      957 |                 940 | -1.78% |
| Working Set (MB)    |       54 |                  54 |  0.00% |
| Build Time (ms)     |    1,198 |               1,229 | +2.59% |
| Start Time (ms)     |    1,095 |               1,091 | -0.37% |
| Published Size (KB) |  369,839 |             369,839 |  0.00% |


| application           | baseline                  | tls-command-caching       |         |
| --------------------- | ------------------------- | ------------------------- | ------- |
| CPU Usage (%)         |                        96 |                        95 |  -1.04% |
| Cores usage (%)       |                     2,678 |                     2,654 |  -0.90% |
| Working Set (MB)      |                       577 |                       571 |  -1.04% |
| Private Memory (MB)   |                     1,323 |                     1,316 |  -0.53% |
| Build Time (ms)       |                     9,709 |                     6,703 | -30.96% |
| Start Time (ms)       |                     1,783 |                     1,775 |  -0.45% |
| Published Size (KB)   |                    96,645 |                    96,649 |  +0.00% |
| Symbols Size (KB)     |                        52 |                        52 |   0.00% |
| .NET Core SDK Version | 8.0.100-preview.3.23170.2 | 8.0.100-preview.3.23170.2 |         |


| load                   | baseline  | tls-command-caching |         |
| ---------------------- | --------- | ------------------- | ------- |
| CPU Usage (%)          |        38 |                  38 |   0.00% |
| Cores usage (%)        |     1,075 |               1,053 |  -2.05% |
| Working Set (MB)       |        48 |                  48 |   0.00% |
| Private Memory (MB)    |       363 |                 363 |   0.00% |
| Start Time (ms)        |         0 |                   0 |         |
| First Request (ms)     |       108 |                 116 |  +7.41% |
| Requests/sec           |   453,098 |             431,989 |  -4.66% |
| Requests               | 6,841,540 |           6,522,919 |  -4.66% |
| Mean latency (ms)      |      1.18 |                1.23 |  +4.24% |
| Max latency (ms)       |     21.85 |               19.58 | -10.39% |
| Bad responses          |         0 |                   0 |         |
| Socket errors          |         0 |                   0 |         |
| Read throughput (MB/s) |    594.58 |              566.88 |  -4.66% |
| Latency 50th (ms)      |      1.05 |                1.11 |  +5.71% |
| Latency 75th (ms)      |      1.29 |                1.37 |  +6.20% |
| Latency 90th (ms)      |      1.63 |                1.72 |  +5.52% |
| Latency 99th (ms)      |      4.16 |                4.03 |  -3.12% |

(executed against 3363a30)

**Comment by roji** [comment]
2nd run with perf counters:

| db                  | baseline | tls-command-caching |         |
| ------------------- | -------- | ------------------- | ------- |
| CPU Usage (%)       |       35 |                  34 |  -2.86% |
| Cores usage (%)     |      975 |                 940 |  -3.59% |
| Working Set (MB)    |       54 |                  53 |  -1.85% |
| Build Time (ms)     |    1,179 |               1,174 |  -0.42% |
| Start Time (ms)     |    1,269 |               1,107 | -12.77% |
| Published Size (KB) |  369,839 |             369,839 |   0.00% |


| application                             | baseline                  | tls-command-caching       |          |
| --------------------------------------- | ------------------------- | ------------------------- | -------- |
| CPU Usage (%)                           |                        97 |                        96 |   -1.03% |
| Cores usage (%)                         |                     2,704 |                     2,685 |   -0.70% |
| Working Set (MB)                        |                       563 |                       558 |   -0.89% |
| Private Memory (MB)                     |                     1,325 |                     1,313 |   -0.91% |
| Build Time (ms)                         |                     3,657 |                     3,630 |   -0.74% |
| Start Time (ms)                         |                     1,746 |                     1,828 |   +4.70% |
| Published Size (KB)                     |                    96,645 |                    96,645 |    0.00% |
| Symbols Size (KB)                       |                        52 |                        52 |    0.00% |
| .NET Core SDK Version                   | 8.0.100-preview.3.23170.2 | 8.0.100-preview.3.23170.2 |          |
| Max CPU Usage (%)                       |                        97 |                        96 |   -0.94% |
| Max Working Set (MB)                    |                       586 |                       585 |   -0.16% |
| Max GC Heap Size (MB)                   |                       382 |                       390 |   +2.32% |
| Size of committed memory by the GC (MB) |                       497 |                       495 |   -0.43% |
| Max Number of Gen 0 GCs / sec           |                      5.00 |                      6.00 |  +20.00% |
| Max Number of Gen 1 GCs / sec           |                      1.00 |                      2.00 | +100.00% |
| Max Number of Gen 2 GCs / sec           |                      1.00 |                      1.00 |    0.00% |
| Max Time in GC (%)                      |                      1.00 |                      7.00 | +600.00% |
| Max Gen 0 Size (B)                      |                 5,041,896 |                 8,200,456 |  +62.65% |
| Max Gen 1 Size (B)                      |                41,860,848 |                44,896,632 |   +7.25% |
| Max Gen 2 Size (B)                      |                18,648,416 |                18,584,128 |   -0.34% |
| Max LOH Size (B)                        |                   339,432 |                   241,072 |  -28.98% |
| Max POH Size (B)                        |                 4,411,360 |                 4,415,480 |   +0.09% |
| Max Allocation Rate (B/sec)             |             1,674,853,640 |             1,687,889,192 |   +0.78% |
| Max GC Heap Fragmentation               |                        70 |                        32 |  -53.76% |
| # of Assemblies Loaded                  |                        87 |                        87 |    0.00% |
| Max Exceptions (#/s)                    |                       962 |                       948 |   -1.46% |
| Max Lock Contention (#/s)               |                     2,697 |                     6,038 | +123.88% |
| Max ThreadPool Threads Count            |                        49 |                        48 |   -2.04% |
| Max ThreadPool Queue Length             |                       122 |                        93 |  -23.77% |
| Max ThreadPool Items (#/s)              |                   701,203 |                   666,152 |   -5.00% |
| Max Active Timers                       |                        12 |                        13 |   +8.33% |
| IL Jitted (B)                           |                   410,049 |                   411,934 |   +0.46% |
| Methods Jitted                          |                     4,492 |                     4,519 |   +0.60% |


| load                   | baseline  | tls-command-caching |        |
| ---------------------- | --------- | ------------------- | ------ |
| CPU Usage (%)          |        38 |                  38 |  0.00% |
| Cores usage (%)        |     1,069 |               1,058 | -1.03% |
| Working Set (MB)       |        48 |                  48 |  0.00% |
| Private Memory (MB)    |       363 |                 363 |  0.00% |
| Start Time (ms)        |         0 |                   0 |        |
| First Request (ms)     |       112 |                 116 | +3.57% |
| Requests/sec           |   454,197 |             436,617 | -3.87% |
| Requests               | 6,858,246 |           6,592,231 | -3.88% |
| Mean latency (ms)      |      1.18 |                1.22 | +3.39% |
| Max latency (ms)       |     21.40 |               20.91 | -2.29% |
| Bad responses          |         0 |                   0 |        |
| Socket errors          |         0 |                   0 |        |
| Read throughput (MB/s) |    596.02 |              572.95 | -3.87% |
| Latency 50th (ms)      |      1.05 |                1.10 | +4.76% |
| Latency 75th (ms)      |      1.29 |                1.35 | +4.65% |
| Latency 90th (ms)      |      1.63 |                1.71 | +4.91% |
| Latency 99th (ms)      |      4.50 |                4.23 | -6.00% |

**Comment by vonzshik** [comment]
OK. Doesn't look like there are any improvements, so I'm going to close this.

**Pull request closed without merging**
