### PR TITLE
OrdinalIgnoreCase is unnecessary

### PR DESCRIPTION
**Pull request by benaadams**
https://www.techempower.com/benchmarks/#section=code&hw=peak&test=json
> General requirements
3. Specific characters and character case matter.

### CODE REVIEW

**Comment by DamianEdwards** [comment]
Technically, I believe they're referring to casing in responses, not URIs. The language around URIs is "The **recommended** URI is /json"

**Comment by benaadams** [comment]
yeah but linux stuff is generally case sensitive so bbc news is linux; you can tell as if you go here its ok

`http://www.bbc.co.uk/news/scotland` but if you capitalize it 404s `http://www.bbc.co.uk/news/Scotland`

**Comment by benaadams** [comment]
yeah but linux stuff is generally case sensitive so bbc news is linux; you can tell as if you go here its ok

`http://www.bbc.co.uk/news/scotland` but if you capitalize it 404s `http://www.bbc.co.uk/news/Scotland`

If you are being compared to linux frameworks on linux; should use the same rules? Windows is just generally more forgiving.

**Comment by DamianEdwards** [comment]
Sure, but the other examples I tried in the TechEmpower benchmarks didn't care about casing AFAICT. All that said, we probably don't need to have this line anyway (everything here is controlled).

**Comment by benaadams** [comment]
Ordinal has improves https://github.com/dotnet/coreclr/pull/2825

**Comment by DamianEdwards** [comment]
Wow, that's cool. We'll get that benefit whether we remove the case-insensitive check or not though.

**Comment by DamianEdwards** [comment]
Bah, OK you win, removing code is good :smile:

**Comment by benaadams** [comment]
> We'll get that benefit whether we remove the case-insensitive check or not though.

Not if you fall through to next item

**Comment by DamianEdwards** [comment]
Oh good point, although that's less of an issue with my latest changes (only enable specific scenarios).

**Comment by benaadams** [comment]
And.... just for completeness https://tools.ietf.org/html/rfc7230#section-2.7.3
> The scheme and host are case-insensitive and normally provided in lowercase; all other
   components are compared in a case-sensitive manner.

However with controllers and methods being camel case and paths generally being lowercase (ignoring @shanselman's wild blog post paths); probably would want to be case insensitive for general aspnet path testing.

**Pull request merged**
