### PR TITLE
Proxy use HeaderNames rather than string const

### PR DESCRIPTION
**Pull request by benaadams**
It be faster after https://github.com/aspnet/AspNetCore/pull/9341

/cc @sebastienros

### CODE REVIEW

**Comment by sebastienros** [comment]
Will that really be faster?

**Comment by benaadams** [comment]
Will be a `ReferenceEquals` test rather than a `string.Equals(..., OrdinalIgnoreCase)`

**Comment by benaadams** [comment]
Might not be huge, but every little helps :)

**Comment by sebastienros** [comment]
Meh!

**Pull request merged**
