### PR TITLE
Inline platform plaintext

### PR DESCRIPTION
**Pull request by BrennanConroy**
10.7m -> 11.7m

### CODE REVIEW

**Comment by sebastienros** [comment]
What are the numbers for the other platform benchmarks?

**Comment by BrennanConroy** [comment]
What other ones?

**Comment by sebastienros** [comment]
How many scenarios does this file contain? 😁

**Comment by BrennanConroy** [comment]
The db ones probably will not benefit. I tried Fortunes and it went down a couple dozen thousand RPS

**Pull request merged**
