### PR TITLE
Update client to netcoreapp2.1

### PR DESCRIPTION
**Pull request by BrennanConroy**

### CODE REVIEW

**Comment by BrennanConroy** [comment]
We're probably going to wait for 2.1 to RTM before merging this

**Comment by BrennanConroy** [comment]
@sebastienros Take a look please

**Comment by sebastienros** [comment]
LGTM, but we'll have to redeploy everything. And I also need to change the scenarios to have 2.1 be the new baseline.

**Comment by sebastienros** [comment]
What have you done !!! OMG

**Pull request merged**
