### PR TITLE
Remove duplicate call

### PR DESCRIPTION
**Pull request by jo-ninja**
Remove repeating property access/method call on "plaintext" response.

### CODE REVIEW

**Comment by jo-ninja** [comment]
I also did a simple benchmark using BenchmarkDotNet trying to simulate the "plaintext" response:
https://gist.github.com/jo-ninja/127a3ebec6e6e5f1fca4a6dbfcb46e64

Result:
image

From the result, we can see that there is a slight improvement in both response speed and memory usage for `ExecuteResultWithSavedResponseAndLengthVarAsync`. Not a big improvement, but would be interested to see how it will make a difference.

**Comment by jo-ninja** [comment]
Addresses #425

**Comment by sebastienros** [comment]
Let me run some benchmarks on this branch before we merge it.

**Comment by davidfowl** [comment]
@sebastienros did you run it?

**Comment by sebastienros** [comment]
Not yet, can you? Or I'll do it tomorrow first thing.

**Comment by davidfowl** [comment]
@sebastienros how do you usually run a branch of benchmarks?

**Comment by sebastienros** [comment]
-r bechmarks@branch
________________________________

**Comment by sebastienros** [comment]
In this case it's -r https://.../reposurl@branch

**Comment by davidfowl** [comment]
So specifically:

```
-r https://github.com/jo-ninja/benchmarks.git@plaintext-remove-duplicate
```

**Comment by davidfowl** [comment]
Seems to work:

```JSON
"source": {
"branchOrCommit": "plaintext-remove-duplicate",
"repository": "https://github.com/jo-ninja/benchmarks.git",
"project": "src/Benchmarks/Benchmarks.csproj",
"dockerFile": null
}
```

**Comment by sebastienros** [comment]
Both will work, just easier on the command line. And documented.

**Comment by davidfowl** [comment]
@sebastienros I was looking at the job description posted to the server to see if the command line worked.

**Comment by davidfowl** [comment]
Looks every so slightly faster but it's probably noise:

## Before

```
[10:51:29.771] RequestsPerSecond:           463771
[10:51:29.771] Latency on load (ms):        5.7
[10:51:29.771] Max CPU (%):                 97
[10:51:29.771] WorkingSet (MB):             395
[10:51:29.771] Startup Main (ms):           536
[10:51:29.772] First Request (ms):          336.2
[10:51:29.772] Latency (ms):                0.6
[10:51:29.772] Socket Errors:               0
[10:51:29.772] Bad Responses:               0
[10:51:29.772] SDK:                         2.2.0-preview1-007522
[10:51:29.772] Runtime:                     2.1.0-preview2-26314-02
[10:51:29.772] ASP.NET Core:                2.1.0-preview3-32040
```

## After

```
[10:52:38.912] RequestsPerSecond:           464542
[10:52:38.912] Latency on load (ms):        5.5
[10:52:38.912] Max CPU (%):                 97
[10:52:38.912] WorkingSet (MB):             394
[10:52:38.912] Startup Main (ms):           513
[10:52:38.912] First Request (ms):          335.4
[10:52:38.912] Latency (ms):                0.7
[10:52:38.912] Socket Errors:               0
[10:52:38.912] Bad Responses:               0
[10:52:38.912] SDK:                         2.2.0-preview1-007522
[10:52:38.913] Runtime:                     2.1.0-preview2-26314-02
[10:52:38.913] ASP.NET Core:                2.1.0-preview3-32040
```

This doesn't hurt so it's fine to merge but it doesn't look like it helps anything really.

**Comment by sebastienros** [comment]
GTG

**Pull request merged**
