### PR TITLE
HttpClient benchmark - add generated headers

### PR DESCRIPTION
**Pull request by CarnaViire**
Add configuration to set number of generated headers with static values and number of generated headers with values changing per request.

Add flag to use `HttpClient.DefaultRequestHeaders` for static headers.

cc @ManickaP @MihaZupan

### CODE REVIEW

**Review by ManickaP — APPROVED** [review]
LGTM, thanks.
The only thing I'm wondering about is if we really need this level of configurability, e.g. whether to use default headers collection or not. On the other hand, the code for this is fairly simple so it doesn't incur high costs of maintenance. I'm just thinking aloud here, nothing serious though :smile:

**Comment by CarnaViire** [comment]
DefaultRequestHeaders was what @MihaZupan actually suggested, saying that HttpClient+DefaultRequestHeaders should be faster than HttpMessageInvoker, so I was curious and wanted to be able to test that theory. Also would be handy if we would have LLHTTP later to compare to them too.

**Comment by MihaZupan** [comment]
Right, `DefaultRequestHeaders` is the only case I know of where `HttpClient` can end up outperforming `HttpMessageInvoker`. It has a [more efficient copy loop](https://github.com/dotnet/runtime/blob/c4422a0a1687ddc0869565cbbc8459e1f0e11737/src/libraries/System.Net.Http/src/System/Net/Http/Headers/HttpHeaders.cs#L528) than what you can achieve with `HttpMessageInvoker`.

And it's especially efficient for the `DynamicRequestHeadersCount = 0` case (i.e. all headers come from `DefaultRequestHeaders`) due to [this fast path we added in 7.0](https://github.com/dotnet/runtime/blob/c4422a0a1687ddc0869565cbbc8459e1f0e11737/src/libraries/System.Net.Http/src/System/Net/Http/Headers/HttpHeaders.cs#L536-L555)

**Comment by CarnaViire** [comment]
@sebastienros could you please take a look?

**Comment by sebastienros** [comment]
Look or merge?

**Comment by CarnaViire** [comment]
If you're ok with it then merge -- I have @ManickaP's approve above

**Pull request merged**
