### PR TITLE
Update BenchmarkConfigurationHelpers.cs

### PR DESCRIPTION
**Pull request by davidfowl**
/cc @geoffkizer

### CODE REVIEW

**Comment by sebastienros** [comment]
You mean it was using the wrong values, as in the ones in the driver and not what is actually passed to the client?

**Comment by davidfowl** [comment]
> You mean it was using the wrong values, as in the ones in the driver and not what is actually passed to the benchmarked app?

Yes that's what @geoffkizer was saying, I'm trying to find the code.

**Comment by geoffkizer** [comment]
I tried to run libuv by passing –webHost KestrelLibuv to BenchmarksDriver, but the trace showed it was still using sockets.  

In my trace I see the benchmark driver is passing --kestrelTransport Libuv to the PlatformBenchmark app, but it looks like the PlatformBenchmark app ignores this currently...

**Comment by davidfowl** [comment]
Yep found it https://github.com/aspnet/benchmarks/blob/43582d9a88d8c9e0e919ff7b7bc61f922fae017e/src/BenchmarksServer/Startup.cs#L1349.

This is why we need to just get rid of the driver arguments 😄

**Comment by davidfowl** [comment]
@sebastienros I'm going to merge this

**Comment by geoffkizer** [comment]
I just pulled this and I'm still seeing Sockets used

**Comment by davidfowl** [comment]
Try again. I just pushed another fix.

**Comment by geoffkizer** [comment]
yep, working now.  thanks!

**Pull request merged**
