### PR TITLE
Update to RazorSlices 0.4.0 & tweak Fortunes templates accordingly

### PR DESCRIPTION
**Pull request by DamianEdwards**
RazorSlices 0.4.0 will be released shortly and this is pre-emptive update to the benchmarks to react.

image

### CODE REVIEW

**Comment by sebastienros** [comment]
I mean I like it

**Comment by DamianEdwards** [comment]
@sebastienros that was an oversight on my part. I'd assume we'd make the same optimization there in the spirit of the benchmarks, i.e. it's a reasonable optimization given the scenario.

**Comment by DamianEdwards** [comment]
I think you and I are still in disagreement on this point :smile:

**Comment by sebastienros** [comment]
Can you run the numbers on Minimal with and without the change on the template?

**Comment by DamianEdwards** [comment]
> Can you run the numbers on Minimal with and without the change on the template?

Can do, but will have to wait until tomorrow.

**Comment by DamianEdwards** [comment]
OK here's the full results. The impact in the minimal test is actually higher in some ways, with the optimized version being 1.3% faster on average, and only 0.99% slower than 0.3.0, vs. 2.26% slower in the unoptimized 0.4.0 version.

image

**Review by sebastienros — APPROVED** [review]
Makes me sad, but hey, someone has to be here and you did the work so this will me my contribution.

**Pull request merged**
