### PR TITLE
Remove IsDatabase flag

### LINKED ISSUE #1812: Wrong connection string for npgsql
Recently broken:

```
Database: PostgreSql
ConnectionString: Server=;Database=hello_world;User Id=benchmarkdbuser;Password=benchmarkdbpass;Maximum Pool Size=18;Enlist=false;Max Auto Prepare=4;Multiplexing=true;Write Coalescing Buffer Threshold Bytes=1000
[STDERR] Unhandled exception. System.ArgumentException: Host can't be null
[STDERR]    at Npgsql.NpgsqlConnectionStringBuilder.PostProcessAndValidate()
[STDERR]    at Npgsql.NpgsqlSlimDataSourceBuilder.PrepareConfiguration()
[STDERR]    at Npgsql.NpgsqlSlimDataSourceBuilder.Build()
[STDERR]    at Npgsql.NpgsqlDataSourceBuilder.Build()
[STDERR]    at Npgsql.NpgsqlDataSource.Create(String connectionString)
[STDERR]    at PlatformBenchmarks.RawDb..ctor(ConcurrentRandom random, AppSettings appSettings) in C:\Users\Administrator\AppData\Local\Temp\benchmarks-agent\benchmarks-server-8092\mq0y5lkj.sc4\benchmarks\src\BenchmarksApps\TechEmpower\PlatformBenchmarks\Data\RawDb.cs:line 32
[STDERR]    at PlatformBenchmarks.Program.BuildWebHost(String[] args) in C:\Users\Administrator\AppData\Local\Temp\benchmarks-agent\benchmarks-server-8092\mq0y5lkj.sc4\benchmarks\src\BenchmarksApps\TechEmpower\PlatformBenchmarks\Program.cs:line 75
[STDERR]    at PlatformBenchmarks.Program.Main(String[] args) in C:\Users\Administrator\AppData\Local\Temp\benchmarks-agent\benchmarks-server-8092\mq0y5lkj.sc4\benchmarks\src\BenchmarksApps\TechEmpower\PlatformBenchmarks\Program.cs:line 37
[STDERR]    at PlatformBenchmarks.Program.<Main>(String[] args)
```

https://dev.azure.com/dnceng/internal/_build/results?buildId=2134528&view=logs&j=d3806cb9-9f29-58a2-f37f-9b640ae897dc&t=0464fd43-95cd-5f5a-6725-81098dcbe5d0

### PR DESCRIPTION
**Pull request by sebastienros**
This should only be opt-in at build

Fixes #1812

### CODE REVIEW

**Comment by roji** [comment]
Oops :)

**Comment by DamianEdwards** [comment]
Hmm perhaps we should consider adding build configurations that set it then, as it's kinda painful to work with locally.

**Comment by sebastienros** [comment]
We have the same code that works for all scenarios too, but for Platform we wanted to squeeze as much as we possible.

> we should consider adding build configurations that set it then

The scenarios in the yml set the `/p:IsDatabase=true` when required. I don't understand what you mean though.

**Comment by DamianEdwards** [comment]
When working on the code locally in VS. If one is working on database benchmarks then they have to manually add that property to the csproj to get the related code to activate. If we had a build configuration defined in the csproj that set that property it could just be selected in the VS drop-down. The automated builds wouldnt need to change.

**Comment by sebastienros** [comment]
> If we had a build configuration defined in the csproj

That was my question, I did know or think that it was an option. That's why I can't be a PM.

**Comment by roji** [comment]
We can also have the environment variable set (Rider has this option, or it can be done in Windows). It's true that it's slightly annoying but...

**Comment by DamianEdwards** [comment]
The environment variable doesn't help from an IDE point of view, e.g. ensuring relevant code is "in context" and active in the IDE for IntelliSense, build errors, etc. I'll send a PR to add some build configurations.

**Pull request merged**
