### PR TITLE
Fix BenchmarkDotNet results formatting on Linux

### PR DESCRIPTION
**Pull request by adamsitnik**
Anytime I was trying to run some BDN benchmarks on Linux machine I was getting a strangely formatted output:

obraz

So I have fixed it:

obraz

/cc @sebastienros @roji

### CODE REVIEW

**Comment by roji** [comment]
Strange - I run BDN on Linux all the time and the output has always been fine - maybe it's related to something specific in your output... But anyway great to see Linux support improving :)

**Comment by adamsitnik** [comment]
@roji which OS and cmd are you using? I am using powershell from Windows 10.

I most probably hit some edge case bug with weird whitespaces handling, hence I just added `.Trim()` to the code and did not investigate it too much.

**Comment by roji** [comment]
Ah, you're on Powershell on Linux? It may be related to that...

I work on xubuntu 19.04 using zsh in the standard xfce4-terminal. In any case makes sense to have a trim there...

**Comment by sebastienros** [comment]
Let's see how it goes with it

**Pull request merged**
