### PR TITLE
Remove manual YARP PGO runs

### PR DESCRIPTION
**Pull request by MihaZupan**
No need for these anymore now that PGO is on by default.

### CODE REVIEW

**Review by sebastienros — APPROVED** [review]
Should I also delete the old results from the db then?

**Comment by sebastienros** [comment]
I found a few benchmarks being slower even though overall it's a positive change, haven't filed an issue yet. Adding @EgorBo for awareness.

**Comment by sebastienros** [comment]
Maybe the difference is between dynamic PGO and full PGO.

**Comment by MihaZupan** [comment]
Is ASP.NET also R2R'd?
For reference, with YARP scenarios here, the difference from this trade-off appear to be ~0, only Kestrel with HTTP/2 is slightly worse off.

**Comment by EgorBo** [comment]
> Is ASP.NET also R2R'd?

Should be so, yes

**Comment by MihaZupan** [comment]
Thanks, Egor.

> Should I also delete the old results from the db then?

I think we can, not much point in tracking that difference from YARP's perspective.

**Pull request merged**
