### PR TITLE
Bump Npgsql/EF Core to 6.0.0-preview3

### PR DESCRIPTION
**Pull request by roji**
Since EF Core 6.0.0-preview3 contains the stronger reflection fix (https://github.com/dotnet/efcore/pull/24090), this should make our dashboard work again.

This should start showing the perf improvements from https://github.com/dotnet/efcore/issues/23611.

/cc @ajcvickers

### CODE REVIEW

**Comment by sebastienros** [comment]
I tried to run it and it didn't work, the packages are not available on our feeds I assume

```
crank --config https://raw.githubusercontent.com/aspnet/Benchmarks/main/scenarios/database.benchmarks.yml --scenario fortunes_ef --profile aspnet-perf-lin --application.source.branchOrCommit EFPreview3 --application.source.repository https://github.com/roji/AspNetBenchmarks --application.framework net6.0
```

```
/tmp/benchmarks-agent/benchmarks-server-1/1rm1kp1o.2d1/AspNetBenchmarks/src/Benchmarks/Benchmarks.csproj : error NU1102: Unable to find package Npgsql.EntityFrameworkCore.PostgreSQL with version (>= 6.0.0-preview3)
/tmp/benchmarks-agent/benchmarks-server-1/1rm1kp1o.2d1/AspNetBenchmarks/src/Benchmarks/Benchmarks.csproj : error NU1102:   - Found 60 version(s) in dotnet-public [ Nearest version: 6.0.0-preview2 ]
```

**Comment by sebastienros** [comment]
@wtgodbe can you add Npgsql and EF.SQlserver preview3 on the feeds please?

**Comment by wtgodbe** [comment]
> @wtgodbe can you add Npgsql and EF.SQlserver preview3 on the feeds please?

Done

**Comment by sebastienros** [comment]
It worked, thanks

**Pull request merged**
