### PR TITLE
Serialize a JObject

### PR DESCRIPTION
**Pull request by benaadams**
Seems to go a bit better

/cc @JamesNK

### CODE REVIEW

**Comment by mikeharder** [comment]
@benaadams: Do you have any numbers showing the perf impact of this change?

**Comment by JamesNK** [comment]
I believe the rules of the test are that the type is serialized using a generic mechanism rather than is hard coded. Do any of the JSON tests from others do something like this?

**Comment by benaadams** [comment]
> 1. For each request, an object mapping the key message to Hello, World! must be instantiated.
> 2. The recommended URI is /json.
> 3. A JSON serializer must be used to convert the object to JSON.
> 4. The response text must be {"message":"Hello, World!"}, but white-space variations are acceptable.
> 5. The response content length should be approximately 28 bytes.
> ...

Is still doing 1 & 3 ?

**Comment by mikeharder** [comment]
@benaadams: This doesn't compile for me.  I think you're missing a using directive.

```
Middleware\JsonMiddleware.cs(39,35): error CS0246: The type or namespace name 'JObject' could not be found (are you missing a using directive or an assembly reference?)
```

**Comment by mikeharder** [comment]
Assuming `JObject.WriteTo()` is faster than `JsonSerializer.Serialize()`, my next question would be why can't the implementation of `JsonSerializer.Serialize()` use the same code as this PR?  I don't know much about Json.NET so this may be a bad question.

**Comment by benaadams** [comment]
Added missing using

**Comment by mikeharder** [comment]
I only collected 3 samples, but I don't see a measurable perf benefit on our physical hardware:

Branch | RPS | Average Deviation
------------ | ------------- | -------------
dev | 282,448 | 2,096
benaadams:jobject | 282,278 | 1756

**Comment by benaadams** [comment]
@JamesNK isn't giving me easy wins... 😺

**Comment by benaadams** [comment]
Though `StreamWriter` why you allocate so much! O_o but that's corefx...

**Comment by benaadams** [comment]
Main allocations in Json test is from `StreamWriter` so I've added a PR for that https://github.com/dotnet/corefx/pull/23727

**Comment by davidfowl** [comment]
We have an HttpResponseStreamWriter built in that we could use. It does the pooling using the array pool.

**Comment by jkotalik** [comment]
See https://github.com/aspnet/HttpAbstractions/blob/dev/src/Microsoft.AspNetCore.WebUtilities/HttpResponseStreamWriter.cs

**Comment by benaadams** [comment]
@davidfowl sounds like a target to beat 😉

**Pull request closed without merging**
