### PR TITLE
Minimal appHost.config

### PR DESCRIPTION
**Pull request by shirhatti**
Remove all unnecessary modules from appHost.config

### CODE REVIEW

**Comment by shirhatti** [comment]
dotnet run -c release -- --server "..." --client "..." -j ..\Benchmarks\benchmarks.plaintext.json -n Plaintext --webHost IISInProcess -o Benchmarks@dev
```
[06:28:29.508] RequestsPerSecond:           28932
[06:28:29.508] Latency on load (ms):        87.5
[06:28:29.512] Max CPU (%):                 49761
[06:28:29.516] WorkingSet (MB):             274
[06:28:29.517] Startup Main (ms):           648
[06:28:29.517] First Request (ms):          927.7
[06:28:29.518] Latency (ms):                1
[06:28:29.519] Total Requests:              436,795
[06:28:29.521] Duration: (ms)               15100
[06:28:29.526] Socket Errors:               0
[06:28:29.526] Bad Responses:               0
[06:28:29.528] SDK:                         2.2.0-preview1-007522
[06:28:29.529] Runtime:                     2.1.0-preview2-26314-02
[06:28:29.529] ASP.NET Core:                2.1.0-preview3-32019
```

dotnet run -c release -- --server "..." --client "..." -j ..\Benchmarks\benchmarks.plaintext.json -n Plaintext --webHost IISInProcess -o Benchmarks@shirhatti/iis
```
[06:34:18.859] RequestsPerSecond:           30029
[06:34:18.859] Latency on load (ms):        47.2
[06:34:18.863] Max CPU (%):                 216
[06:34:18.866] WorkingSet (MB):             12
[06:34:18.866] Startup Main (ms):           629
[06:34:18.867] First Request (ms):          5.2
[06:34:18.872] Latency (ms):                0.7
[06:34:18.876] Total Requests:              453,377
[06:34:18.878] Duration: (ms)               15100
[06:34:18.879] Socket Errors:               0
[06:34:18.879] Bad Responses:               453377
[06:34:18.880] SDK:                         2.2.0-preview1-007522
[06:34:18.881] Runtime:                     2.1.0-preview2-26314-02
[06:34:18.881] ASP.NET Core:                2.1.0-preview3-32019
```

**Comment by sebastienros** [comment]
> Bad Responses:               453377

**Comment by shirhatti** [comment]
😢 I'll fix it on Monday

**Comment by shirhatti** [comment]
dotnet run -c release -- --server "..." --client "..." -j ..\Benchmarks\benchmarks.plaintext.json -n Plaintext --webHost IISInProcess -o Benchmarks@dev
```
[12:38:43.700] RequestsPerSecond:           41513
[12:38:43.700] Latency on load (ms):        54
[12:38:43.701] Max CPU (%):                 570
[12:38:43.702] WorkingSet (MB):             274
[12:38:43.703] Startup Main (ms):           735
[12:38:43.703] First Request (ms):          719
[12:38:43.704] Latency (ms):                1.7
[12:38:43.704] Total Requests:              626,552
[12:38:43.704] Duration: (ms)               15090
[12:38:43.705] Socket Errors:               0
[12:38:43.705] Bad Responses:               0
[12:38:43.705] SDK:                         2.2.0-preview1-007522
[12:38:43.706] Runtime:                     2.1.0-preview2-26314-02
[12:38:43.706] ASP.NET Core:                2.1.0-preview3-32042
```

dotnet run -c release -- --server "..." --client "..." -j ..\Benchmarks\benchmarks.plaintext.json -n Plaintext --webHost IISInProcess -o Benchmarks@shirhatti/iis
```
[12:51:14.480] RequestsPerSecond:           21200
[12:51:14.480] Latency on load (ms):        104.6
[12:51:14.480] Max CPU (%):                 428
[12:51:14.480] WorkingSet (MB):             275
[12:51:14.480] Startup Main (ms):           580
[12:51:14.480] First Request (ms):          660.5
[12:51:14.481] Latency (ms):                0.9
[12:51:14.482] Total Requests:              320,105
[12:51:14.482] Duration: (ms)               15100
[12:51:14.483] Socket Errors:               0
[12:51:14.483] Bad Responses:               0
[12:51:14.483] SDK:                         2.2.0-preview1-007522
[12:51:14.484] Runtime:                     2.1.0-preview2-26314-02
[12:51:14.484] ASP.NET Core:                2.1.0-preview3-32042
```

**Comment by shirhatti** [comment]
@jkotalik Can you help make sense of these numbers?

**Comment by sebastienros** [comment]
Remove `-o Benchmarks@shirhatti/iis` and use `-r Benchmarks@shirhatti/iis`

**Comment by shirhatti** [comment]
Looked a comparative trace between the two scenarios with the help of @bangbingsyb.
Most of the excess CPU is spent in w3_context::SetupStateMachine in iiscore.dll.

I'm going to try again after adding back in the `UriCacheModule`.

**Comment by shirhatti** [comment]
```
[05:17:42.135] RequestsPerSecond:           45287
[05:17:42.135] Latency on load (ms):        49.3
[05:17:42.137] Max CPU (%):                 575
[05:17:42.140] WorkingSet (MB):             271
[05:17:42.141] Startup Main (ms):           513
[05:17:42.141] First Request (ms):          673.8
[05:17:42.141] Latency (ms):                0.9
[05:17:42.142] Total Requests:              683,590
[05:17:42.142] Duration: (ms)               15090
[05:17:42.143] Socket Errors:               0
[05:17:42.143] Bad Responses:               0
[05:17:42.143] SDK:                         2.2.0-preview1-007522
[05:17:42.144] Runtime:                     2.1.0-preview2-26314-02
[05:17:42.144] ASP.NET Core:                2.1.0-preview3-32047
```

**Comment by jkotalik** [comment]
@shirhatti why did it waste all of that time in the state machine?

**Comment by shirhatti** [comment]
`UriCacheModule` caches configuration at the URL level. Without that, nativerd.dll has re-read IIS configuration on every single request

**Comment by bangbingsyb** [comment]
@jkotalik During state machine setup phase, it actually wasted lots of CPU cycles in reading the configuration for each request and we saw native reader called CONFIG_CACHE::CacheMiss like crazy. That's why I ended up suspecting the root cause be the missing of UriCacheModule - it caches the configuration for a particular URL upon the first request to that URL. For all later requests to the same URL, it can simply fetch the configuration from the cached version inside W3_URL_INFO.

Since the request processing cycle for this scenario is extremely short and simple, this config mechanism actually plays a significant role :)

**Comment by davidfowl** [comment]
I dunno how I feel about this change. How many people actually run like this?

**Comment by shirhatti** [comment]
> How many people actually run like this?

Zero.

The only reason I want this change is because it eliminates so much cruft.

**Comment by mikeharder** [comment]
I would recommend testing two IIS configurations:

1. Highest-performance configuration if you only care about running ASP.NET Core in IIS.  The highest-performance configuration may also be the minimal config.
2. Typical customer configuration.  This may be the out-of-the-box defaults, or the result of following public docs to configure IIS and ASP.NET Core.

**Comment by pakrym** [comment]
We might want to explore the ability to replace apphost config the same way we replace dll's. So one can benchmark whatever required.

**Comment by bangbingsyb** [comment]
Swapping apphost for the test is quite handy, we uses this mechanism in IIS performance test to switch between scenarios.

**Pull request closed without merging**
